# Generated by Django 5.1.1 on 2026-01-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_import_symptoms_data'),
    ]

    operations = [
    ]
